imports:
    - { resource: serializer.yaml }
    - { resource: services.yaml }
    - { resource: swagger.yaml }

fast_crud:
    exception_interceptor:
        enabled: true
        effective_pattern: /^\/(api|manage)\/.*$/