app.swagger_ui:
    path: /swagger-ui.html
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
    path: /swagger-ui.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }